version: '3.7'
services:
  order-db:
    image: postgres:12.2-alpine
    container_name: order-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
  test-db:
    build: ./OrderService.IntegrationTests/Database
    container_name: test-db
    ports:
      - "54433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db